name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Backup database on server (only if exists)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if docker ps -a --format '{{.Names}}' | grep -q '^rfc-db$$'; then
              cd /root/rfc
              mkdir -p export
              make extract
            else
              echo "No container to backup — skipping."
            fi

      - name: 📤 Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/rfc"
          overwrite: true
          strip_components: 1
